int cube[24];
int a, b, c, d, e, f, g, h, i, j, k, l, m, tmp; 
void tu();
void tui();
void tl();
void tli();
void tf();
void tfi();
void tr();
void tri();
void tb();
void tbi();
void td();
void tdi();
void twist();